### ISSUE TITLE
[NEW FEATURE] Micro-Meta App / Explorer integration

### ISSUE THREAD

**Issue by strambc** [WU-BIMAC/MicroMetaExplorer#1]
First Window

![image](https://user-images.githubusercontent.com/4050585/231283370-c252913e-f726-42d3-b4c9-c42e86954a1d.png)

- [x] Change name of buttons to: Micro-Meta App  and Micro-Meta Explorer
- [ ] Insert tooltips for the two buttons (use available Tooltip template)
- [ ] Add TBD text to go under the main name (similar to what is present in Micro-Meta App)

**Micro-Meta Explorer**
Button Main Title --> Micro-Meta Explorer
Button Sub Title --> Compare the hardware components of different available microscopes and select the one you are interested in."
Tooltip title --> "Micro-Meta Explorer"
Tooltip body --> "Click this button to launch Micro-Meta Explorer."

=======
**Micro-Meta App button** 
Button Main Title --> Micro-Meta App
Button Sub Title --> Collect information about the microscope hardware components and the image acquisition settings associated with specific datasets.
Tooltip title --> "Micro-Meta App"
Tooltip body --> "Click this button to launch Micro-Meta App."

- [ ] Define Logos for buttons (same as Favicons for the two components)
- [ ] Redefine Micro-Meta App logo to make it more generic.
